export interface Ingredient {
  name: string;
  amount: string;
  store: 'D1' | 'Ara' | 'Dolarciyt' | 'Cualquiera';
}

export interface Recipe {
  id: string;
  name: string;
  emoji: string;
  mealType: 'desayuno' | 'almuerzo' | 'cena' | 'snack';
  prepTime: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  servings: number;
  difficulty: 'fácil' | 'medio';
  portableForWork: boolean;
  ingredients: Ingredient[];
  steps: string[];
  tip: string;
  tags: string[];
}

export const RECIPES: Recipe[] = [
  {
    id: 'avena_proteica',
    name: 'Avena Protéica con Frutas',
    emoji: '🍌',
    mealType: 'desayuno',
    prepTime: 10,
    calories: 320,
    protein: 18,
    carbs: 45,
    fat: 7,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: true,
    tags: ['alto protéico', 'sin gluten', 'rápido'],
    ingredients: [
      { name: 'Avena en hojuelas', amount: '1/2 taza (50g)', store: 'D1' },
      { name: 'Leche desnatada o agua', amount: '1 taza', store: 'D1' },
      { name: 'Banano maduro', amount: '1 pequeño', store: 'Cualquiera' },
      { name: 'Huevos', amount: '2 claras o 1 entero', store: 'D1' },
      { name: 'Canela en polvo', amount: '1 cucharadita', store: 'D1' },
      { name: 'Miel de abeja', amount: '1 cucharadita', store: 'Ara' },
    ],
    steps: [
      'Cocina la avena con la leche a fuego medio por 5 minutos, revolviendo constantemente.',
      'Mientras tanto, bate las claras de huevo y mézclalas con la avena al final de la cocción.',
      'Cocina 2 minutos más hasta que quede cremosa.',
      'Sirve con banano en rodajas, canela y un toque de miel.',
    ],
    tip: 'Prepárala la noche anterior en la nevera (overnight oats) para llevar al trabajo en un tarro.',
  },
  {
    id: 'huevos_vegetales',
    name: 'Revuelto de Huevos con Vegetales',
    emoji: '🍳',
    mealType: 'desayuno',
    prepTime: 12,
    calories: 280,
    protein: 22,
    carbs: 15,
    fat: 14,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: false,
    tags: ['keto', 'alto protéico', 'sin carbohidratos'],
    ingredients: [
      { name: 'Huevos', amount: '3', store: 'D1' },
      { name: 'Espinacas', amount: '1 puñado', store: 'Ara' },
      { name: 'Tomate chonto', amount: '1 mediano', store: 'Cualquiera' },
      { name: 'Cebolla cabezona', amount: '1/4', store: 'Cualquiera' },
      { name: 'Aceite de oliva o canola', amount: '1 cucharadita', store: 'D1' },
      { name: 'Sal y pimienta', amount: 'al gusto', store: 'D1' },
    ],
    steps: [
      'Pica finamente la cebolla y el tomate.',
      'Sofríe la cebolla en aceite caliente por 2 minutos.',
      'Agrega el tomate y las espinacas, cocina 1 minuto.',
      'Bate los huevos, viértelos y revuelve hasta que cuajen.',
      'Salpimienta al gusto y sirve caliente.',
    ],
    tip: 'Agrega queso campesino bajo en grasa para más proteína.',
  },
  {
    id: 'wrap_pollo',
    name: 'Wrap de Pollo Saludable',
    emoji: '🌯',
    mealType: 'almuerzo',
    prepTime: 20,
    calories: 420,
    protein: 35,
    carbs: 40,
    fat: 12,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: true,
    tags: ['para llevar', 'meal prep', 'alto protéico'],
    ingredients: [
      { name: 'Pechuga de pollo', amount: '150g', store: 'D1' },
      { name: 'Tortilla integral', amount: '1 grande', store: 'Ara' },
      { name: 'Lechuga', amount: '2 hojas', store: 'Cualquiera' },
      { name: 'Tomate', amount: '1/2', store: 'Cualquiera' },
      { name: 'Aguacate', amount: '1/4', store: 'Cualquiera' },
      { name: 'Mostaza o yogurt griego', amount: '1 cucharada', store: 'D1' },
      { name: 'Limón', amount: '1/2', store: 'Cualquiera' },
    ],
    steps: [
      'Sazona el pollo con sal, pimienta y un toque de limón.',
      'Cocina el pollo a la plancha 6-7 minutos por cada lado.',
      'Deja reposar 3 minutos y corta en tiras.',
      'Calienta la tortilla 30 segundos en sartén seca.',
      'Arma el wrap: tortilla, lechuga, tomate, pollo, aguacate y mostaza.',
      'Enrolla firme y corta por la mitad.',
    ],
    tip: 'Envuelve en papel aluminio y lleva al trabajo. Se mantiene bien 4 horas.',
  },
  {
    id: 'sopa_lentejas',
    name: 'Sopa de Lentejas Colombiana',
    emoji: '🍲',
    mealType: 'almuerzo',
    prepTime: 35,
    calories: 380,
    protein: 22,
    carbs: 52,
    fat: 6,
    servings: 2,
    difficulty: 'fácil',
    portableForWork: false,
    tags: ['meal prep', 'económico', 'alto protéico', 'vegano'],
    ingredients: [
      { name: 'Lentejas', amount: '1 taza', store: 'D1' },
      { name: 'Papa criolla', amount: '2 medianas', store: 'Cualquiera' },
      { name: 'Zanahoria', amount: '1', store: 'Cualquiera' },
      { name: 'Hogao (tomate y cebolla)', amount: '3 cucharadas', store: 'Cualquiera' },
      { name: 'Comino y color', amount: 'al gusto', store: 'D1' },
      { name: 'Cilantro', amount: '1 rama', store: 'Cualquiera' },
    ],
    steps: [
      'Remoja las lentejas 30 minutos antes (opcional pero reduce tiempo de cocción).',
      'Sofríe el hogao con comino y color por 3 minutos.',
      'Agrega las lentejas y cubre con 4 tazas de agua.',
      'Hierve 20 minutos, agrega papa y zanahoria en cubos.',
      'Cocina 15 minutos más hasta que las verduras estén suaves.',
      'Ajusta sal y decora con cilantro picado.',
    ],
    tip: 'Prepárala en cantidad y congela porciones para la semana.',
  },
  {
    id: 'bowl_arroz_pollo',
    name: 'Bowl de Arroz Integral con Pollo',
    emoji: '🍛',
    mealType: 'almuerzo',
    prepTime: 30,
    calories: 450,
    protein: 38,
    carbs: 48,
    fat: 10,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: true,
    tags: ['meal prep', 'alto protéico', 'balanceado'],
    ingredients: [
      { name: 'Arroz integral', amount: '1/2 taza seco', store: 'D1' },
      { name: 'Pechuga de pollo', amount: '150g', store: 'D1' },
      { name: 'Brócoli', amount: '1 taza', store: 'Ara' },
      { name: 'Zanahoria', amount: '1/2', store: 'Cualquiera' },
      { name: 'Salsa soya light', amount: '1 cucharada', store: 'Dolarciyt' },
      { name: 'Ajo en polvo', amount: '1/2 cucharadita', store: 'D1' },
    ],
    steps: [
      'Cocina el arroz integral según las instrucciones del paquete (tarda más que el blanco).',
      'Sazona el pollo con ajo, sal y pimienta. Cocina a la plancha.',
      'Saltea brócoli y zanahoria con un toque de salsa soya 5 minutos.',
      'Arma el bowl: arroz, pollo en tiras, vegetales salteados.',
      'Añade más salsa soya o limón al gusto.',
    ],
    tip: 'Prepára 3 porciones el domingo y guarda en túrper en la nevera.',
  },
  {
    id: 'filete_pescado',
    name: 'Filete de Pescado con Verduras',
    emoji: '🐟',
    mealType: 'cena',
    prepTime: 20,
    calories: 280,
    protein: 32,
    carbs: 18,
    fat: 9,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: false,
    tags: ['bajo en calorías', 'omega 3', 'ligero'],
    ingredients: [
      { name: 'Filete de tilapia o corvina', amount: '200g', store: 'D1' },
      { name: 'Limones', amount: '2', store: 'Cualquiera' },
      { name: 'Ajo', amount: '2 dientes', store: 'Cualquiera' },
      { name: 'Zucchini', amount: '1', store: 'Ara' },
      { name: 'Pimentón rojo', amount: '1/2', store: 'Cualquiera' },
      { name: 'Aceite de oliva', amount: '1 cucharada', store: 'D1' },
    ],
    steps: [
      'Marina el pescado con limón, ajo picado, sal y pimienta 10 minutos.',
      'Corta zucchini y pimentón en bastones.',
      'Saltea las verduras 4 minutos en aceite de oliva.',
      'Cocina el pescado en la misma sartén 4 minutos por lado.',
      'Sirve el pescado sobre las verduras con limón extra.',
    ],
    tip: 'La tilapia en D1 es muy económica y alta en proteína. Perfecta para cena ligera.',
  },
  {
    id: 'sopa_verduras',
    name: 'Sopa de Verduras Proteica',
    emoji: '🥣',
    mealType: 'cena',
    prepTime: 25,
    calories: 220,
    protein: 18,
    carbs: 28,
    fat: 4,
    servings: 2,
    difficulty: 'fácil',
    portableForWork: false,
    tags: ['bajo en calorías', 'reconfortante', 'hidratante'],
    ingredients: [
      { name: 'Pechuga de pollo', amount: '100g', store: 'D1' },
      { name: 'Calabaza', amount: '1 taza', store: 'Cualquiera' },
      { name: 'Zanahoria', amount: '1', store: 'Cualquiera' },
      { name: 'Apio', amount: '2 tallos', store: 'Ara' },
      { name: 'Caldo de pollo bajo en sodio', amount: '3 tazas', store: 'D1' },
      { name: 'Cilantro y sal', amount: 'al gusto', store: 'Cualquiera' },
    ],
    steps: [
      'Hierve el pollo en el caldo 15 minutos. Retira y desmenuza.',
      'En el mismo caldo agrega las verduras en cubos.',
      'Cocina 12 minutos hasta que estén tiernas.',
      'Regresa el pollo desmenuzado.',
      'Ajusta sal y sirve con cilantro fresco.',
    ],
    tip: 'Perfecta para antes de dormir. Muy baja en calorías y llena.',
  },
  {
    id: 'ensalada_atun',
    name: 'Ensalada de Atún Premium',
    emoji: '🥗',
    mealType: 'cena',
    prepTime: 10,
    calories: 260,
    protein: 28,
    carbs: 20,
    fat: 8,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: true,
    tags: ['rápido', 'sin cocina', 'alto protéico'],
    ingredients: [
      { name: 'Atún en agua (lata)', amount: '1 lata 170g', store: 'D1' },
      { name: 'Lechuga romana', amount: '2 tazas', store: 'Ara' },
      { name: 'Tomate cherry', amount: '10', store: 'Ara' },
      { name: 'Pepino', amount: '1/2', store: 'Cualquiera' },
      { name: 'Aguacate', amount: '1/4', store: 'Cualquiera' },
      { name: 'Aceite de oliva y limón', amount: '1 cucharada c/u', store: 'D1' },
    ],
    steps: [
      'Escurre muy bien el atún.',
      'Pica la lechuga, tomates y pepino.',
      'Mezcla todo en un bowl grande.',
      'Agrega el aguacate en cubos encima.',
      'Adereza con aceite de oliva, limón, sal y pimienta.',
    ],
    tip: 'Sin cocina en absoluto. La ensalada más rápida y nutritiva. Lista en 10 minutos.',
  },
  {
    id: 'yogurt_frutas',
    name: 'Yogurt con Granola y Frutas',
    emoji: '🍓',
    mealType: 'snack',
    prepTime: 5,
    calories: 180,
    protein: 12,
    carbs: 28,
    fat: 3,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: true,
    tags: ['rápido', 'probiticos', 'para llevar'],
    ingredients: [
      { name: 'Yogurt griego natural', amount: '150g', store: 'D1' },
      { name: 'Granola', amount: '2 cucharadas', store: 'Ara' },
      { name: 'Fresas o mora', amount: '1/2 taza', store: 'Cualquiera' },
      { name: 'Miel', amount: '1 cucharadita', store: 'D1' },
    ],
    steps: [
      'Coloca el yogurt en un vaso o bowl.',
      'Agrega la granola encima.',
      'Añade las frutas cortadas.',
      'Termina con un hilo de miel.',
    ],
    tip: 'Llévalo en un tarro mason con tapa. Mantén la granola aparte para que no se ablande.',
  },
  {
    id: 'batido_verde',
    name: 'Batido Verde Energizante',
    emoji: '🥬',
    mealType: 'snack',
    prepTime: 5,
    calories: 160,
    protein: 8,
    carbs: 30,
    fat: 2,
    servings: 1,
    difficulty: 'fácil',
    portableForWork: true,
    tags: ['detox', 'energizante', 'vitaminas'],
    ingredients: [
      { name: 'Espinacas baby', amount: '1 puñado', store: 'Ara' },
      { name: 'Banano congelado', amount: '1', store: 'Cualquiera' },
      { name: 'Mango', amount: '1/2 taza', store: 'Cualquiera' },
      { name: 'Leche de coco o agua', amount: '1 taza', store: 'Dolarciyt' },
      { name: 'Jengibre fresco', amount: 'trozo pequeño', store: 'Cualquiera' },
    ],
    steps: [
      'Congela el banano la noche anterior para textura cremosa.',
      'Pon todos los ingredientes en la licuadora.',
      'Licua a velocidad alta 60 segundos.',
      'Sirve inmediatamente o en termo para llevar.',
    ],
    tip: 'Las espinacas no se sienten en el sabor pero dan nutrientes potentes. Perfecta post-entreno.',
  },
];

export const MEAL_TYPES = [
  { id: 'desayuno', label: 'Desayuno', emoji: '☀️', time: '6am - 9am' },
  { id: 'almuerzo', label: 'Almuerzo', emoji: '🌞', time: '12pm - 2pm' },
  { id: 'cena', label: 'Cena', emoji: '🌙', time: '6pm - 8pm' },
  { id: 'snack', label: 'Snack', emoji: '🍎', time: 'Entre comidas' },
];

export const STORES = [
  { name: 'D1', color: '#EF4444', description: 'Económico y cercano' },
  { name: 'Ara', color: '#F59E0B', description: 'Variedad y calidad' },
  { name: 'Dolarciyt', color: '#10B981', description: 'Productos especiales' },
];
